version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker-file.yml
    ports:
      - "5161:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=postgresql://ecommerce_db_opaz_user:PAIwNjLmCsAm6WsEmM4qoJbFRKTyQxvT@dpg-d99s99jeo5us7391rsc0-a.singapore-postgres.render.com/ecommerce_db_opaz
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
